name: Fetch Coop Data

on:
  schedule:
    - cron: '0 5 * * *'  # 毎日朝5時に実行
    - cron: '0 17 * * *'  # 毎日夕方17時に実行
  workflow_dispatch:  # 手動実行のトリガー

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # リポジトリをチェックアウト

    - name: Set up Python
      uses: actions/setup-python@v4  # Pythonをセットアップ
      with:
        python-version: '3.11'  # Python 3.11を使用

    - name: Upgrade pip
      run: python -m pip install --upgrade pip  # pipをアップグレード

    - name: Install dependencies
      run: pip install bs4 pypdf requests git+https://github.com/Kotetsu0000/discord_webhook.git # 依存関係をインストール

    - name: Fetch Coop Data
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: python fetch_coop_data.py  # データを取得

    - name: Commit and push if changes
      if: github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        if [ "$(git diff --shortstat)" != "" ]; then
          git add .
          git commit -m "GitHub Actions: Fetch Coop Data"
          git push origin HEAD:${GITHUB_REF}
        fi